name: 'Terraform Operations'
description: 'Comprehensive Terraform initialization, planning, and application with destructive change detection'

inputs:
  working-directory:
    description: 'Working directory containing Terraform configuration'
    required: true
    default: './terraform/app'
  terraform-version:
    description: 'Terraform version to install'
    required: false
    default: '1.6.0'
  backend-bucket:
    description: 'S3 bucket for Terraform state'
    required: true
  backend-key:
    description: 'S3 key for Terraform state'
    required: false
    default: 'app/terraform.tfstate'
  backend-region:
    description: 'AWS region for Terraform state'
    required: true
  dynamodb-table:
    description: 'DynamoDB table for Terraform state locking'
    required: true

outputs:
  has-destructive-changes:
    description: 'Whether destructive changes were detected'
    value: ${{ steps.plan.outputs.has_destructive_changes }}
  lambda-production-function-url:
    description: 'Production Lambda Function URL'
    value: ${{ steps.outputs.outputs.lambda_function_url_production }}
  lambda-preview-function-url:
    description: 'Preview Lambda Function URL'
    value: ${{ steps.outputs.outputs.lambda_function_url_preview }}
  access-allow-origin-production:
    description: 'Production CORS allow origin'
    value: ${{ steps.outputs.outputs.access-allow-origin-production }}
  access-allow-origin-preview:
    description: 'Preview CORS allow origin'
    value: ${{ steps.outputs.outputs.access-allow-origin-preview }}
  next-public-api-base-url-production:
    description: 'Production API base URL'
    value: ${{ steps.outputs.outputs.next-public-api-base-url-production }}
  next-public-site-url-production:
    description: 'Production site URL'
    value: ${{ steps.outputs.outputs.next-public-site-url-production }}
  next-public-trusted-domains-production:
    description: 'Production trusted domains'
    value: ${{ steps.outputs.outputs.next-public-trusted-domains-production }}
  next-public-api-base-url-preview:
    description: 'Preview API base URL'
    value: ${{ steps.outputs.outputs.next-public-api-base-url-preview }}
  next-public-site-url-preview:
    description: 'Preview site URL'
    value: ${{ steps.outputs.outputs.next-public-site-url-preview }}
  next-public-trusted-domains-preview:
    description: 'Preview trusted domains'
    value: ${{ steps.outputs.outputs.next-public-trusted-domains-preview }}
  terraform-outputs:
    description: 'JSON string of all Terraform outputs'
    value: ${{ steps.outputs.outputs.terraform_outputs }}

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        BACKEND_BUCKET: ${{ inputs.backend-bucket }}
        BACKEND_KEY: ${{ inputs.backend-key }}
        BACKEND_REGION: ${{ inputs.backend-region }}
        DYNAMODB_TABLE: ${{ inputs.dynamodb-table }}
      run: |
        set -euo pipefail
        terraform init \
          -backend-config="bucket=$BACKEND_BUCKET" \
          -backend-config="key=$BACKEND_KEY" \
          -backend-config="region=$BACKEND_REGION" \
          -backend-config="dynamodb_table=$DYNAMODB_TABLE"

    - name: Terraform Plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform plan -detailed-exitcode -out=tfplan

        # 破壊的変更の検出（要件REQ-102準拠）
        if terraform show -json tfplan | jq -e '.resource_changes[]? | select(.change.actions[] | contains("delete"))' > /dev/null; then
          echo "has_destructive_changes=true" >> $GITHUB_OUTPUT
          echo "⚠️ 破壊的変更が検出されました（要件に従い自動継続）"
          terraform show -json tfplan | jq '.resource_changes[] | select(.change.actions[] | contains("delete"))'
        else
          echo "has_destructive_changes=false" >> $GITHUB_OUTPUT
          echo "✅ 破壊的変更は検出されませんでした"
        fi

    - name: Terraform Apply
      uses: nick-fields/retry@v3.0.1
      env:
        TF_WORKDIR: ${{ inputs.working-directory }}
      with:
        timeout_minutes: 15
        max_attempts: 3
        retry_on: error
        command: |
          cd "$TF_WORKDIR"
          terraform apply -auto-approve tfplan

    - name: Extract Terraform Outputs
      id: outputs
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # JSON形式でTerraform出力を取得
        terraform output -json > tf_outputs.json
        
        echo "🔍 Terraform Outputs Debug:"
        echo "Available outputs:"
        terraform output
        echo ""
        echo "🔗 Lambda Function URLs:"
        echo "Production: $(terraform output -raw lambda_production_function_url 2>/dev/null || echo 'NOT_FOUND')"
        echo "Preview: $(terraform output -raw lambda_preview_function_url 2>/dev/null || echo 'NOT_FOUND')"
        echo ""
        
        # GitHub Outputsに個別の値を設定（既存ワークフロー互換性のため）
        echo "lambda_function_name_production=$(terraform output -raw lambda_production_function_name)" >> $GITHUB_OUTPUT
        echo "lambda_function_name_preview=$(terraform output -raw lambda_preview_function_name)" >> $GITHUB_OUTPUT
        echo "lambda_function_url_production=$(terraform output -raw lambda_production_function_url)" >> $GITHUB_OUTPUT
        echo "lambda_function_url_preview=$(terraform output -raw lambda_preview_function_url)" >> $GITHUB_OUTPUT
        echo "aws_role_arn=$(terraform output -raw github_actions_role_arn)" >> $GITHUB_OUTPUT
        echo "project_name=$(terraform output -raw project_name)" >> $GITHUB_OUTPUT
        echo "access-allow-origin-production=$(terraform output -raw access_allow_origin_production)" >> $GITHUB_OUTPUT
        echo "access-allow-origin-preview=$(terraform output -raw access_allow_origin_preview)" >> $GITHUB_OUTPUT
        echo "next-public-api-base-url-production=$(terraform output -raw lambda_production_function_url)" >> $GITHUB_OUTPUT
        echo "next-public-site-url-production=$(terraform output -raw next_public_site_url_production)" >> $GITHUB_OUTPUT
        echo "next-public-trusted-domains-production=$(terraform output -raw next_public_trusted_domains_production)" >> $GITHUB_OUTPUT
        echo "next-public-api-base-url-preview=$(terraform output -raw lambda_preview_function_url)" >> $GITHUB_OUTPUT
        echo "next-public-site-url-preview=$(terraform output -raw next_public_site_url_preview)" >> $GITHUB_OUTPUT
        echo "next-public-trusted-domains-preview=$(terraform output -raw next_public_trusted_domains_preview)" >> $GITHUB_OUTPUT
        
        # JSON出力をアクションアウトプットに設定
        echo "terraform_outputs=$(cat tf_outputs.json | jq -c .)" >> $GITHUB_OUTPUT

        # セキュリティ改善：詳細ログ出力を最小化
        echo "🔧 Terraform操作が正常に完了しました"
        echo "  出力値数: $(terraform output -json | jq 'keys | length')"