services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./app/server:/home/bun/server
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - ACCESS_ALLOW_ORIGIN=${ACCESS_ALLOW_ORIGIN}
      - ACCESS_ALLOW_METHODS=${ACCESS_ALLOW_METHODS}
      - ACCESS_ALLOW_HEADERS=${ACCESS_ALLOW_HEADERS}
    tty: true

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./app/client:/home/bun/client
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - DB_TABLE_PREFIX=${DB_TABLE_PREFIX}
    tty: true

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5432:5432"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TABLE_PREFIX=${DB_TABLE_PREFIX}
    tty: true
