services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./app/server:/home/bun/server
    environment:
      - NODE_ENV=development
      - SERVER_PORT=${SERVER_PORT}
      - ACCESS_ALLOW_ORIGIN=${ACCESS_ALLOW_ORIGIN}
      - ACCESS_ALLOW_METHODS=${ACCESS_ALLOW_METHODS}
      - ACCESS_ALLOW_HEADERS=${ACCESS_ALLOW_HEADERS}
    tty: true

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./app/client:/home/bun/client
    environment:
      - NODE_ENV=development
      - CLIENT_PORT=${CLIENT_PORT}
    tty: true
