name: Setup Environment
description: Determine deployment environment (production or preview)

inputs:
  environment-override:
    description: 'Override environment type (production or preview). If empty, auto-detect from event context.'
    required: false
    default: ''

outputs:
  environment-type:
    description: 'Deployment environment type: production or preview'
    value: ${{ steps.determine.outputs.environment-type }}
  is-production:
    description: 'true if production environment, false otherwise'
    value: ${{ steps.determine.outputs.is-production }}
  is-preview:
    description: 'true if preview environment, false otherwise'
    value: ${{ steps.determine.outputs.is-preview }}

runs:
  using: composite
  steps:
    - id: determine
      shell: bash
      run: |
        # ç’°å¢ƒåˆ¤å®šãƒ­ã‚¸ãƒƒã‚¯
        # 1. environment-override ãŒæŒ‡å®šã•ã‚Œã¦ã„ã‚Œã°ãã‚Œã‚’ä½¿ç”¨
        # 2. PRãƒžãƒ¼ã‚¸ã‚¤ãƒ™ãƒ³ãƒˆãªã‚‰production
        # 3. ãã‚Œä»¥å¤–ï¼ˆpreview workflowç­‰ï¼‰ã¯preview

        OVERRIDE="${{ inputs.environment-override }}"

        if [[ -n "$OVERRIDE" ]]; then
          # æ‰‹å‹•å®Ÿè¡Œæ™‚ã®ç’°å¢ƒæŒ‡å®šã‚’å„ªå…ˆ
          ENV_TYPE="$OVERRIDE"
          echo "ðŸ”§ Environment override specified: $ENV_TYPE"
        elif [[ "${{ github.event_name }}" == "pull_request" ]] && [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
          # PRãƒžãƒ¼ã‚¸æ™‚ã¯production
          ENV_TYPE="production"
          echo "âœ… PR merged to main: production environment"
        else
          # ãã®ä»–ã®å ´åˆã¯preview
          ENV_TYPE="preview"
          echo "ðŸ” Default: preview environment"
        fi

        # å‡ºåŠ›å€¤ã‚’è¨­å®š
        echo "environment-type=$ENV_TYPE" >> $GITHUB_OUTPUT

        if [[ "$ENV_TYPE" == "production" ]]; then
          echo "is-production=true" >> $GITHUB_OUTPUT
          echo "is-preview=false" >> $GITHUB_OUTPUT
        else
          echo "is-production=false" >> $GITHUB_OUTPUT
          echo "is-preview=true" >> $GITHUB_OUTPUT
        fi

        echo "ðŸ“‹ Environment determined: $ENV_TYPE"
