name: 'Deployment Logger'
description: 'Record deployment history with timestamps and metadata for audit purposes'

inputs:
  event-type:
    description: 'Type of deployment event (start, success, failure)'
    required: true
  component:
    description: 'Component being deployed (infrastructure, backend, frontend, database)'
    required: true
  version:
    description: 'Version or commit SHA being deployed'
    required: false
    default: ${{ github.sha }}
  environment:
    description: 'Target environment (production, preview)'
    required: false
    default: 'production'
  details:
    description: 'Additional deployment details'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Record Deployment Event
      shell: bash
      env:
        INPUT_EVENT_TYPE: ${{ inputs.event-type }}
        INPUT_COMPONENT: ${{ inputs.component }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_DETAILS: ${{ inputs.details }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        # デプロイ記録の基本情報
        TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

        # ログエントリを生成
        LOG_ENTRY="[$TIMESTAMP] $INPUT_EVENT_TYPE - $INPUT_COMPONENT deployment"
        LOG_ENTRY="$LOG_ENTRY | Actor: $GITHUB_ACTOR"
        LOG_ENTRY="$LOG_ENTRY | Environment: $INPUT_ENVIRONMENT"
        LOG_ENTRY="$LOG_ENTRY | Branch: $GITHUB_REF_NAME"

        if [ -n "$INPUT_DETAILS" ]; then
          LOG_ENTRY="$LOG_ENTRY | Details: $INPUT_DETAILS"
        fi

        # ログファイルに記録（GitHubアクションサマリーにも出力）
        echo "$LOG_ENTRY" >> deployment.log
        echo "📋 $LOG_ENTRY" >> "$GITHUB_STEP_SUMMARY"

        # イベント種別に応じた詳細ログ
        case "$INPUT_EVENT_TYPE" in
          "start")
            echo "🚀 Started deploying $INPUT_COMPONENT to $INPUT_ENVIRONMENT" >> "$GITHUB_STEP_SUMMARY"
            ;;
          "success")
            echo "✅ Successfully deployed $INPUT_COMPONENT to $INPUT_ENVIRONMENT" >> "$GITHUB_STEP_SUMMARY"
            ;;
          "failure")
            echo "❌ Failed to deploy $INPUT_COMPONENT to $INPUT_ENVIRONMENT" >> "$GITHUB_STEP_SUMMARY"
            echo "🔗 Check logs: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> "$GITHUB_STEP_SUMMARY"
            ;;
        esac

    - name: Upload Deployment Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: deployment-log-${{ github.run_id }}-${{ inputs.component }}-${{ inputs.event-type }}
        path: deployment.log
        retention-days: 90