name: 'Deployment Logger'
description: 'Record deployment history with timestamps and metadata for audit purposes'

inputs:
  event-type:
    description: 'Type of deployment event (start, success, failure)'
    required: true
  component:
    description: 'Component being deployed (infrastructure, backend, frontend, database)'
    required: true
  version:
    description: 'Version or commit SHA being deployed'
    required: false
    default: ${{ github.sha }}
  environment:
    description: 'Target environment (production, preview)'
    required: false
    default: 'production'
  details:
    description: 'Additional deployment details'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Record Deployment Event
      shell: bash
      run: |
        # デプロイ記録の基本情報
        TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
        COMMIT_SHORT=$(echo "${{ inputs.version }}" | cut -c1-8)
        
        # ログエントリを生成
        LOG_ENTRY="[$TIMESTAMP] ${{ inputs.event-type }} - ${{ inputs.component }} deployment"
        LOG_ENTRY="$LOG_ENTRY | Actor: ${{ github.actor }}"
        LOG_ENTRY="$LOG_ENTRY | Commit: $COMMIT_SHORT"
        LOG_ENTRY="$LOG_ENTRY | Environment: ${{ inputs.environment }}"
        LOG_ENTRY="$LOG_ENTRY | Branch: ${{ github.ref_name }}"
        
        if [ -n "${{ inputs.details }}" ]; then
          LOG_ENTRY="$LOG_ENTRY | Details: ${{ inputs.details }}"
        fi
        
        # ログファイルに記録（GitHubアクションサマリーにも出力）
        echo "$LOG_ENTRY" >> deployment.log
        echo "📋 $LOG_ENTRY" >> $GITHUB_STEP_SUMMARY
        
        # イベント種別に応じた詳細ログ
        case "${{ inputs.event-type }}" in
          "start")
            echo "🚀 Started deploying ${{ inputs.component }} to ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
            ;;
          "success")
            echo "✅ Successfully deployed ${{ inputs.component }} to ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
            ;;
          "failure")
            echo "❌ Failed to deploy ${{ inputs.component }} to ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
            echo "🔗 Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
            ;;
        esac

    - name: Upload Deployment Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: deployment-log-${{ github.run_id }}-${{ inputs.component }}-${{ inputs.event-type }}
        path: deployment.log
        retention-days: 90