name: 'Discord Notification'
description: 'Send deployment status notifications to Discord with customizable embeds'

inputs:
  webhook-url:
    description: 'Discord webhook URL'
    required: true
  status:
    description: 'Deployment status (success or failure)'
    required: true
  title:
    description: 'Notification title'
    required: false
    default: ''
  components:
    description: 'List of deployed components'
    required: false
    default: ''
  commit-sha:
    description: 'Git commit SHA'
    required: false
    default: ${{ github.sha }}
  branch-name:
    description: 'Git branch name'
    required: false
    default: ${{ github.ref_name }}
  actor:
    description: 'GitHub actor who triggered the deployment'
    required: false
    default: ${{ github.actor }}
  repository:
    description: 'GitHub repository'
    required: false
    default: ${{ github.repository }}
  run-id:
    description: 'GitHub Actions run ID'
    required: false
    default: ${{ github.run_id }}
  repository-url:
    description: 'Full repository URL'
    required: false
    default: ''
  frontend-url:
    description: 'Frontend production URL'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Prepare notification content
      id: prepare
      shell: bash
      run: |
        # ステータスに応じた設定
        if [ "${{ inputs.status }}" = "success" ]; then
          TITLE="${{ inputs.title }}"
          if [ -z "$TITLE" ]; then
            TITLE="🚀 Production Deployment Completed Successfully!"
          fi
          COLOR=65280  # 緑色
          
          COMPONENTS="${{ inputs.components }}"
          if [ -z "$COMPONENTS" ]; then
            COMPONENTS="✅ Infrastructure (Terraform)\\n✅ Database (drizzle-kit)\\n✅ Backend (AWS Lambda)\\n✅ Frontend (CloudFlare Pages)"
          fi
          
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "color=$COLOR" >> $GITHUB_OUTPUT
          echo "components=$COMPONENTS" >> $GITHUB_OUTPUT
        else
          TITLE="${{ inputs.title }}"
          if [ -z "$TITLE" ]; then
            TITLE="❌ Production Deployment Failed!"
          fi
          COLOR=16711680  # 赤色
          
          ACTION_MESSAGE="Please check the [job logs](${{ github.server_url }}/${{ inputs.repository }}/actions/runs/${{ inputs.run-id }}) for details and retry the deployment."
          
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "color=$COLOR" >> $GITHUB_OUTPUT
          echo "action_message=$ACTION_MESSAGE" >> $GITHUB_OUTPUT
        fi

    - name: Send Discord notification
      shell: bash
      run: |
        # タイムスタンプを生成
        TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%S.000Z)

        # 成功時と失敗時でペイロードを分岐
        if [ "${{ inputs.status }}" = "success" ]; then
          # 基本フィールドを構築
          FIELDS='[
            {"name": "Commit", "value": "${{ inputs.commit-sha }}", "inline": true},
            {"name": "Branch", "value": "${{ inputs.branch-name }}", "inline": true},
            {"name": "Actor", "value": "${{ inputs.actor }}", "inline": true},
            {"name": "Repository", "value": "${{ inputs.repository }}", "inline": false},
            {"name": "Components Deployed", "value": "${{ steps.prepare.outputs.components }}", "inline": false}'

          # Repository URLが空でない場合は追加
          if [ -n "${{ inputs.repository-url }}" ]; then
            FIELDS="$FIELDS"',
            {"name": "🔗 Repository URL", "value": "${{ inputs.repository-url }}", "inline": false}'
          fi

          # Frontend URLが空でない場合は追加
          if [ -n "${{ inputs.frontend-url }}" ]; then
            FIELDS="$FIELDS"',
            {"name": "🌐 Frontend URL", "value": "${{ inputs.frontend-url }}", "inline": false}'
          fi

          # フィールド配列を閉じる
          FIELDS="$FIELDS"']'

          PAYLOAD=$(cat <<EOF
        {
          "embeds": [{
            "title": "${{ steps.prepare.outputs.title }}",
            "color": ${{ steps.prepare.outputs.color }},
            "fields": $FIELDS,
            "timestamp": "$TIMESTAMP"
          }]
        }
        EOF
          )
        else
          PAYLOAD=$(cat <<EOF
        {
          "embeds": [{
            "title": "${{ steps.prepare.outputs.title }}",
            "color": ${{ steps.prepare.outputs.color }},
            "fields": [
              {"name": "Commit", "value": "${{ inputs.commit-sha }}", "inline": true},
              {"name": "Branch", "value": "${{ inputs.branch-name }}", "inline": true},
              {"name": "Actor", "value": "${{ inputs.actor }}", "inline": true},
              {"name": "Repository", "value": "${{ inputs.repository }}", "inline": false},
              {"name": "Action", "value": "${{ steps.prepare.outputs.action_message }}", "inline": false}
            ],
            "timestamp": "$TIMESTAMP"
          }]
        }
        EOF
          )
        fi
        
        # Discord Webhookに通知を送信
        curl -H "Content-Type: application/json" \
             -d "$PAYLOAD" \
             "${{ inputs.webhook-url }}" \
             --fail --silent --show-error
        
        echo "✅ Discord通知を正常に送信しました"