name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Client (Next.js) のユニットテスト
  client-test:
    name: Client Unit Tests
    uses: ./.github/workflows/unit-test.yml
    with:
      test-type: client
      working-directory: ./app/client
      needs-postgres: false

  # Server (Hono) のユニット/結合テスト
  server-test:
    name: Server Unit Tests
    uses: ./.github/workflows/unit-test.yml
    with:
      test-type: server
      working-directory: ./app/server
      needs-postgres: true

  # E2E (Playwright) テスト
  e2e-test:
    name: E2E Tests
    needs: [client-test, server-test]
    uses: ./.github/workflows/e2e-test.yml