name: CI

on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      concurrency_suffix:
        description: 'Concurrency group suffix to avoid conflicts'
        required: false
        type: string
      cancel_in_progress:
        description: 'Cancel in progress runs'
        required: false
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'workflow_call' && inputs.concurrency_suffix || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'workflow_call' || inputs.cancel_in_progress != false }}

env:
  # CI最適化設定
  ACTIONS_RUNNER_DEBUG: false
  ACTIONS_STEP_DEBUG: false

jobs:
  # Client (Next.js) のユニットテスト
  client-test:
    name: Client Unit Tests
    uses: ./.github/workflows/client-test.yml
    with:
      working-directory: ./app/client

  # Server (Hono) のユニット/結合テスト
  server-test:
    name: Server Unit Tests
    uses: ./.github/workflows/server-test.yml
    with:
      working-directory: ./app/server

  # E2E (Playwright) テスト
  e2e-test:
    name: E2E Tests
    # 完全並行にするか、依存関係を維持するかはプロジェクトの方針次第
    # needs: [client-test, server-test]  # コスト効率重視の場合
    uses: ./.github/workflows/e2e-test.yml
    with:
      concurrency_suffix: ${{ inputs.concurrency_suffix || '' }}
      cancel_in_progress: ${{ inputs.cancel_in_progress != null && inputs.cancel_in_progress || inputs.cancel_in_progress == null }}

  # 全テスト成功の明示的チェック
  all-tests-passed:
    name: All Tests Passed
    runs-on: ubuntu-latest
    needs: [client-test, server-test, e2e-test]
    steps:
      - name: Check all tests passed
        run: echo "✅ All tests (client, server, e2e) passed successfully"
