name: Client Test

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory for the test'
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun Environment
        uses: ./.github/actions/setup-bun
        with:
          working-directory: ${{ inputs.working-directory }}
          cache-key-suffix: client

      - name: Run lint and type check
        working-directory: ${{ inputs.working-directory }}
        run: bun run check

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        env:
          NODE_ENV: test
        run: bun test